### ISSUE TITLE
saving configuration to ubiquiti devices broken

### ISSUE THREAD

**Issue by sanderr** [inmanta/vyos#29]
The check `"Saving configuration to '/tmp/inmanta_tmp'" in out` fails for ubiquiti devices because they now prompt a warning when saving to non-default location: `"saving configuration to non-default location '/tmp/inmanta_tmp'"`.

I'm not sure how to resolve this. This doesn't seem the responsibility of the `vyos` module, but I don't see how the `ubiquiti` module could handle this.

**Comment by sanderr** [comment]
@bartv @wouterdb I know this is far from priority, but if you already happen to have an idea on how this could be resolved I'd like to fix this in my spare time. There's no such thing as overriding handler behavior for a submodule, right?
If you don't immediately see a way to resolve this I guess it will stay in the icebox for some time.

**Comment by bartv** [comment]
You could introduce something like vyos flavours in the vyos module. You have ubiquiti, vyos < 1.2, vyos >= 1.2, danos, ...

**Comment by sanderr** [comment]
Thanks. I'll start with support for "vyos" and "ubiquiti" but I'll try to make it sufficiently generic to allow adding other flavours and version numbers when required.
